### ISSUE TITLE
axe-core-nuget v4.8.0Release

### ISSUE THREAD

**Issue by dequejenn** [dequelabs/axe-core-nuget#113]
Below is everything related to this release

## Dependancies/Blockers
- [x] Requires axe-core to be updated first
    - [x] Has been updated successfully
- [ ] Requires open source version to be completed first 
    - [ ] Has been updated successfully
- [ ] Blocked by in flight work (please list PRs waiting on below)

## Links
- [ ] Release candidate: https://github.com/dequelabs/axe-core-nuget/pull/117
- [ ] ~~Release PR:~~
- [ ] Release audit: https://github.com/dequelabs/axe-core-nuget/pull/117#issuecomment-1742796675
- [ ] ~~Release notes:~~
- [ ] QA Ticket: https://github.com/dequelabs/axe-core-nuget/issues/119
- [ ] ~~Release notes ticket:~~

## Steps
- [x] Updated axe-core
- [x] Ticket created for QA
- [x] QA Signoff on RC
- [ ] Ticket created for release notes
- [ ] Release notes published (if applicable)
- [x] Release audit posted
- [ ] Deployed
- [ ] Sync main back into develop
- [ ] Posted in product-channel

## Additional Steps For AWS Deploys
- [ ] Data migrations:
- [ ] Environment variables:
- [ ] Docker image:
- [ ] Smoke test passed

```[tasklist]
### Tasks
```
